"use client"

import Link from "next/link"
import { Ban } from "lucide-react"

import { Button } from "@/components/ui/button"

export default function UnsafeQRPage() {
  return (
    <div className="min-h-screen flex flex-col justify-center items-center px-4 bg-gradient-to-br from-yellow-50 to-white">
      <div className="max-w-md w-full bg-white p-8 shadow-xl rounded-xl text-center border border-yellow-200">
        <div className="flex justify-center mb-4 text-yellow-600">
          <Ban size={48} />
        </div>
        <h1 className="text-2xl font-bold text-yellow-700 mb-2">
          QR Code Not Recognized
        </h1>
        <p className="text-gray-600 mb-6">
          This QR code was not generated by QR Safe, or the original URL no longer exists in our database.
        </p>
        <p className="text-sm text-gray-500 mb-8">
          Only QR codes created through QR Safe go through URL validation and security checks. If you reached this page by scanning a QR, we recommend avoiding the destination.
        </p>
        <Button asChild>
          <Link href="/">Return to Home</Link>
        </Button>
      </div>
    </div>
  )
}
